[package]
name = "rsign"
version = "0.1.0"
authors = ["Daniel Rangel <daniel@rangel.in>"]
license = "MIT"
readme = "README.md"


[dependencies]
sodiumoxide = "0.0.15"
libsodium-sys = "0.0.15"
base64 = "0.6.0"
clap = "2.26.0"
libc = "0.2"
rpassword = "1.0.0"
chrono = "0.4"

[[bin]]
name = "rsign"
path = "src/bin/main.rs"
