[package]
name = "rsign"
version = "0.1.0"
authors = ["Daniel Rangel <daniel@rangel.in>"]

[dependencies]
sodiumoxide = { path = "sodiumoxide" }
libsodium-sys = { path = "sodiumoxide/libsodium-sys"}
base64 = "0.6.0"
serde = "1.0.10"
serde_derive = "1.0.10"
clap = "2.26.0"
libc = "0.2"
rpassword = "1.0.0"
byteorder = "1"
chrono = "0.4"

[[bin]]
name = "rsign"
path = "bin/main.rs"
