[package]
name = "rsign"
version = "0.1.1"
authors = ["Daniel Rangel <daniel@rangel.in>"]
description = "A command-line tool to sign files and verify signatures."
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "cryptography"]
keywords = ["command-line", "sign", "publickey", "cryptography", "minisign"]
repository = "https://bitbucket.org/danielrangel/rsign"

[dependencies]
sodiumoxide = "0.0.15"
libsodium-sys = "0.0.15"
base64 = "0.6.0"
clap = "2.26.0"
libc = "0.2"
rpassword = "1.0.0"
chrono = "0.4"

[dev-dependencies]
unwrap = "~1.1.0"
