[package]
name = "rsign2"
version = "0.2.0"
authors = ["Frank Denis <github@pureftpd.org>", "Daniel Rangel <daniel@rangel.in>"]
description = "A command-line tool to sign files and verify signatures."
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "cryptography"]
keywords = ["command-line", "sign", "publickey", "cryptography", "minisign"]
repository = "https://github.com/jedisct1/rsign2"
edition = "2015"

[dependencies]
base64 = "0.10"
chrono = "0.4"
clap = "2.33"
dirs = "1.0"
libc = "0.2"
libsodium-sys = "0.2"
rand = "0.6"
rpassword = "3.0"
scrypt = { version = "0.2", default-features = false }
sodiumoxide = "0.2"

[dev-dependencies]
unwrap = "1.2"
